#include <iostream>

using namespace std;

int divide(int);

int main()
{
    int a, b;
    cout<<"enter numbers:"<<endl;
    cin>>a>>b;

    cout<<"divide(a, b)"<<endl;
    cout<<"divide(a)"<<endl;

    return 0;
}

int divide(int a, int b)
{
     if(a%b==0)
    {
      return 1;
    }
    else
    {
      return 0;
    }
}

int divide(int num)
{
  for(int i=2;i<=num/2;i++)
    if "divide"(num)
  }
    {
  return 0,
}
}
return 1;
}
